package com.medicine.reminder.config;
import com.medicine.reminder.util.JwtUtil; import jakarta.servlet.*; import jakarta.servlet.http.*; import org.springframework.context.annotation.*; import org.springframework.security.authentication.*; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.*; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.stereotype.Component; import org.springframework.web.filter.OncePerRequestFilter; import java.io.IOException; import java.util.*;
@Configuration @EnableWebSecurity
public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean SecurityFilterChain security(HttpSecurity http, JwtFilter filter)throws Exception{return http.csrf(c->c.disable()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).exceptionHandling(e->e.authenticationEntryPoint((req,res,ex)->{res.setStatus(HttpServletResponse.SC_UNAUTHORIZED);res.setContentType("application/json");res.getWriter().write("{\"message\":\"Session expired. Please sign in again.\"}");})).authorizeHttpRequests(a->a.requestMatchers("/api/auth/**").permitAll().requestMatchers("/api/**").authenticated().anyRequest().permitAll()).addFilterBefore(filter,UsernamePasswordAuthenticationFilter.class).build();}
 @Component public static class JwtFilter extends OncePerRequestFilter {
  private final JwtUtil jwt; public JwtFilter(JwtUtil jwt){this.jwt=jwt;}
  protected void doFilterInternal(HttpServletRequest req,HttpServletResponse res,FilterChain chain)throws ServletException,IOException {String h=req.getHeader("Authorization");if(h!=null&&h.startsWith("Bearer ")){String t=h.substring(7);if(jwt.valid(t)){var auth=new UsernamePasswordAuthenticationToken(jwt.username(t),null,List.of(new SimpleGrantedAuthority("ROLE_USER")));auth.setDetails(jwt.userId(t));org.springframework.security.core.context.SecurityContextHolder.getContext().setAuthentication(auth);}}chain.doFilter(req,res);}
 }
}
